server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'WDMM430617'
    url: jdbc:mysql://localhost:3306/helathsystem?useSSL=false&serverTimezone=UTC

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true